#!/usr/bin/env bash

DEPLOYDIR="../www.phantom/dist/"
HELPSTRING="--help"
if [[ "$1" == "$HELPSTRING" ]]
then
      echo "To deploy the project to a new public name, run the following command (in a bash environment), replacing \$PUBLIC_NAME with your desired public name:"
      echo ""
      echo "    ./deploy \$PUBLIC_NAME --create"
      echo ""
      echo "If you are deploying to an existing public name, use the following:"
      echo ""
      echo "    ./deploy \$PUBLIC_NAME";
      exit 0
fi

if [ -z "$1" ]
then
      echo "Error: a valid safenet NRS public name must be passed as the first parameter"
      exit 2
fi

(cd ../www.phantom; npm run build)

if [[ ! -d "$DEPLOYDIR" ]]
then
      echo "$DEPLOYDIR does not exist on your filesystem."
fi

CREATESTRING="--create"
if [[ "$2" == "$CREATESTRING" ]]
then
      PUTRESULT=`safe files put "$DEPLOYDIR" "safe://$1" --recursive`
      SAFEPATH="$(echo "$PUTRESULT" | grep -oE "at: \"safe:\/\/[a-zA-Z0-9]+" | grep -oE "safe:\/\/.*")"
      safe nrs create "$1" -l "$SAFEPATH?v=0" && echo "Deployment complete" || echo "Unable to create NRS, NRS may already exist, try re-running this without the --create argument" && exit 1
else
  echo "$DEPLOYDIR"
      safe files sync "$DEPLOYDIR" "safe://$1" --update-nrs --recursive
fi